version : "3"
services:
  zookeeper:
    platform: linux/arm64
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    platform: linux/arm64
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFAK_CREATE_TOPICS: "Topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091,PLAINTEXT_HOST://localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_PORT: 9991
    volumes:
      - /var/run/docker.sock
    depends_on:
      - zookeeper
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 19200:9200
    depends_on:
      - kafka
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:8.5.0
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch
#    ports:
#      - 15601:5601
#  db:
#    container_name: mysql
#    image: mysql
#    environment:
#      MYSQL_DATABASE: cb_counter
#      MYSQL_USER: user
#      MYSQL_PASSWORD: user
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_HOST: '%'
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#    ports:
#      - "3306:3306"
#    volumes:
#      - /tmp/mysql_db
#    restart: always
#    depends_on:
#      - kafka
