### 참고 : https://esbook.kimjmin.net/04-data/4.1-rest-api
### 추가
POST http://localhost:19200/user/_doc/1
Content-Type: application/json

{
  "name": "kim",
  "age": 1
}

### 수정
PUT http://localhost:19200/user/_doc/1
Content-Type: application/json

{
  "name": "kim",
  "age": 10
}

### 일부 데이터만 업데이트
POST http://localhost:19200/user/_update/1
Content-Type: application/json

{
  "doc": {
    "age": 5
  }
}

### 조회
GET http://localhost:19200/user/_doc/1

### id 없이 추가하기
POST http://localhost:19200/user/_doc
Content-Type: application/json

{
  "name": "park",
  "age": 10
}

### 기존 데이터를 덮어쓰지 않게 _doc 대신 _create 사용 가능 : version conflict 에러 발생
PUT http://localhost:19200/user/_create/1
Content-Type: application/json

{
  "name": "gang",
  "age": 1
}

### 찾기
GET http://localhost:19200/user/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "name": "kim"
    }
  }
}

### index 확인
GET http://localhost:19200/user

### search
GET http://localhost:8080/es/search?q=kim
